name: MapRepair
version: '0.6.0'
main: me.wyzebb.maprepair.MapRepair
api-version: '1.17'
author: Wyzebb
description: A simple plugin to repair blocks changes to your worlds - great for minigame maps!

commands:
  maprepair:
    aliases:
      - mr
    description: Run /maprepair for subcommand information!
    usage: /maprepair <subcommand>
    permission: maprepair.command