name: MapRepair
version: '0.5.2'
main: me.wyzebb.maprepair.MapRepair
api-version: '1.17'
author: Wyzebb
description: A simple plugin to repair blocks changes to your worlds - great for minigame maps!

commands:
  maprepair:
    aliases:
      - mr
    description: Map Repair plugin base command - run /maprepair for more information!
    usage: /maprepair <subcommand>
    permission: maprepair.command